services:
  client:
    build:
      context: ./client
      no_cache: true
    container_name: client
    volumes:
      - ./client:/client
    ports:
      - "3000:3000"
    restart: always
  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/ssl.pem:/etc/ssl/ssl.pem
      - ./nginx/cert.key:/etc/ssl/cert.key
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - client
    restart: always
