services:
  client:
    build:
      context: ./client
    container_name: willki-client
    volumes:
      - ./client:/client
    restart: always
  server:
    build:
      context: ./server
    container_name: willki-server
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/mydb
    volumes:
      - ./server:/server
    depends_on:
      - db
    restart: always
  db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=sh
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=mydb
    volumes:
      - ./data:/var/lib/postgresql/data
      - ./postgreSQL/init.sql:/docker-entrypoint-initdb.d/init.sql
  nginx:
    image: nginx:latest
    container_name: willki-nginx
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/ssl.pem:/etc/ssl/ssl.pem
      - ./nginx/cert.key:/etc/ssl/cert.key
    ports:
      - "8080:80"
    depends_on:
      - client
      - server
    restart: always
