services:
  client:
    build:
      context: ./client
    container_name: willki-client
    networks:
      - default
      - willki-shared
    restart: always
  server:
    build:
      context: ./server
    container_name: willki-server
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/mydb
    volumes:
      - ./server:/server
    depends_on:
      - db
    networks:
      - default
      - willki-shared
    restart: always
  db:
    container_name: willki-db
    image: postgres:17
    environment:
      - POSTGRES_USER=sh
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=mydb
    volumes:
      - ./data:/var/lib/postgresql/data
      - ./postgreSQL/init.sql:/docker-entrypoint-initdb.d/init.sql

networks:
  willki-shared:
    name: willki-shared
    external: true
