services:
  client:
    build:
      context: ./client
      no_cache: true
    container_name: client
    volumes:
      - ./client:/client
    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
    restart: always
  server:
    build:
      context: ./server
    container_name: server
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/mydb
    volumes:
      - ./server:/server
    depends_on:
      - db
    restart: always
  db:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=sh
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=mydb
    volumes:
      - ./data:/var/lib/postgresql/data
      - ./postgreSQL/init.sql:/docker-entrypoint-initdb.d/init.sql
  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/ssl.pem:/etc/ssl/ssl.pem
      - ./nginx/cert.key:/etc/ssl/cert.key
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - client
      - server
    restart: always
